Update ssh-to-host script

diff --git a/aws-network-spe-py/ssh-to-host b/aws-network-spe-py/ssh-to-host
--- a/aws-network-spe-py/ssh-to-host
+++ b/aws-network-spe-py/ssh-to-host
@@ -1,6 +1,20 @@
-#!/usr/bin/env bash
+#!/usr/bin/env ../bin/opsh
+# shellcheck shell=bash
 
-set -euo pipefail
+check_pulumi_yaml() {
+    local dir
+    dir="$(pwd)"
+
+    while [[ ! -f "$dir/Pulumi.yaml" && "$dir" != "/" ]]; do
+        dir="$(dirname "$dir")"
+    done
+
+    [[ -f "$dir/Pulumi.yaml" ]]
+}
+
+if ! check_pulumi_yaml; then
+    log::fatal "No Pulumi.yaml file found in the current directory or any of its parents."
+fi
 
 list_nodes() {
     pulumi stack output --show-secrets nodes_name | jq -r '.[]' | nl -v 0
@@ -8,35 +22,36 @@ list_nodes() {
 }
 
 if [[ "$#" -eq 0 ]]; then
-    echo "Usage: $0 <node-index> [command]"
-    echo "Available nodes:"
+    log::info "Usage: $0 <node-index> [command]"
+    log::info "Available nodes:"
     list_nodes
 fi
 
-hostindex=$1 ; shift
+hostindex=$1
+shift
 
 NODES=$(pulumi stack output --show-secrets nodes_name)
 NODE_COUNT=$(echo "$NODES" | jq -r 'length')
 
 if ! [[ "$hostindex" =~ ^[0-9]+$ ]] || [ "$hostindex" -ge "$NODE_COUNT" ]; then
-    echo "Error: Invalid node index '$hostindex'."
-    echo "Available nodes:"
-    echo "$NODES" | jq -r '.[]' | nl -v 0
+    log::error "Invalid node index '$hostindex'."
+    log::info "Available nodes:"
+    log::info "$NODES" | jq -r '.[]' | nl -v 0
     exit 1
 fi
 
-PRIVKEY=$(mktemp)
+PRIVKEY="$(temp::file)"
 
-cleanup () {
+cleanup() {
     rm -f "$PRIVKEY"
 }
 
 trap cleanup EXIT
 
-touch $PRIVKEY
-chmod 600 $PRIVKEY
+touch "$PRIVKEY"
+chmod 600 "$PRIVKEY"
 
-pulumi stack output --show-secrets nodes_private_key | jq -r ".[$hostindex]" - > $PRIVKEY
+pulumi stack output --show-secrets nodes_private_key | jq -r ".[$hostindex]" - >"$PRIVKEY"
 HOSTNAME=$(pulumi stack output nodes_public_ip | jq -r ".[$hostindex]" -)
 
 ssh -o StrictHostKeyChecking=off -o UserKnownHostsFile=/dev/null -i "$PRIVKEY" "admin@$HOSTNAME" "$@"
